### PR TITLE
Add option to control figure size in plots plus fixes

### PR DESCRIPTION
**Pull request by flokno**
* Add option to modify the default figure size of `figsize=(8, 8)` in the plot functions from `outputs`
* Add version stamp to `setup.cfg` so that `pip` can correctly version `effmass`

### CODE REVIEW

**Comment by flokno** [comment]
* add fix when aims is used and output file is not called `calculation.out`

**Comment by flokno** [comment]
(marked as draft until I tested everything I need)

**Comment by flokno** [comment]
Should be fine now. Overall I fixed some bugs and some slight adjustments for my [own small cli script](https://github.com/flokno/scripts/blob/main/aims_effmass).

@lucydot let me know if you disagree with anything.

**Comment by lucydot** [comment]
Sorry for super late reply @flokno and ⭐ thank you ⭐ for your contribution!

**Pull request merged**
